# Explicitly disable auto-detection of Puppeteer/Playwright
[providers]
node = false

[phases.setup]
nixPkgs = ["nodejs", "npm"]
aptPkgs = []

[phases.install]
cmds = [
    "apt-get update",
    "apt-get install -y --no-install-recommends wget gnupg ca-certificates",
    "mkdir -p /etc/apt/keyrings", 
    "wget -qO- https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /etc/apt/keyrings/google-chrome.gpg",
    "echo 'deb [arch=amd64 signed-by=/etc/apt/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google-chrome.list",
    "apt-get update",
    "apt-get install -y --no-install-recommends google-chrome-stable fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libcups2 libdbus-1-3 libdrm2 libgbm1 libgtk-3-0 libnspr4 libnss3 libx11-xcb1 libxcomposite1 libxdamage1 libxrandr2 xdg-utils",
    "npm install"
]

[start]
cmd = "npm start"