[phases.install]
cmds = [
    "apt-get update",
    "apt-get install -y --no-install-recommends wget gnupg ca-certificates",
    "mkdir -p /etc/apt/keyrings",
    "wget -qO- https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /etc/apt/keyrings/google-chrome.gpg",
    "echo 'deb [arch=amd64 signed-by=/etc/apt/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google-chrome.list",
    "apt-get update",
    "apt-get install -y --no-install-recommends google-chrome-stable",
    "npm install"
]

[start]
cmd = "npm start"